# Operaciones básicas

La clase array es muy flexible y permite muchas operaciones entre dos arrays, aunque con algunos requisitos.

## Suma

Por ejemplo las operaciones `suma` y `resta` requieren que los arrays tengan la misma forma, es decir, mismo número y tamaño de las dimensiones.

In [2]:
import numpy as np

# Dos arrays
arr_1 = np.array([1,2,3,4])
arr_2 = np.array([5,6,7,8])

# Los sumamos
arr_1 + arr_2

array([ 6,  8, 10, 12])

Si no tienen la misma forma no podemos sumarlos:

In [3]:
arr_3 = np.array([9,10])
arr_2 + arr_3

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

## Resta

In [4]:
arr_2 - arr_1

array([4, 4, 4, 4])

¿Qué ocurriría si restamos un array a si mismo?

In [5]:
arr_1 - arr_1

array([0, 0, 0, 0])

Pues que obtenemos un array con todos los valores a cero.

## Producto

En el caso del `producto`, la `divisón` y la `potencia` se pueden operar arrays de las mismas dimensiones si el número de columnas de la primera coincide con el número de filas de la segunda:

In [6]:
# Dos arrays
arr_1 = np.array([1,2,3,4])
arr_2 = np.array([2,3,4,5])

# Los multiplicamos
arr_1 * arr_2

array([ 2,  6, 12, 20])

También podemos multiplicar un array por un número:

In [7]:
arr_1 * 10

array([10, 20, 30, 40])

En este caso sería equivalente a multiplicar un `array` con una fila y una columna `1x1`:

In [8]:
arr_1 * np.array(10)

array([10, 20, 30, 40])

## División

Igual que el producto, la división entre arrays se basa en dividir cada elemento de un array por el elemento en la misma posición del otro:

In [9]:
arr_1 / arr_2

array([0.5       , 0.66666667, 0.75      , 0.8       ])

También podemos dividir todos sus elementos por un número:

In [10]:
arr_1 / 2

array([0.5, 1. , 1.5, 2. ])

Algo interesante que podemos hacer con la división es conseguir el arreglo inverso o recíproco dividiendo 1 entre el array:

In [11]:
1 / arr_1

array([1.        , 0.5       , 0.33333333, 0.25      ])

Esto es equivalente hacer la potencia a `-1` del array:

In [13]:
arr_1 ** 2

array([ 1,  4,  9, 16])

No podemos elevar a un entero negativo, pero sí podemos indicar la elevación a`-1.` e indicar un decimal:

In [ ]:
arr_1 ** -1.

Ya que estamos con las potencias, también podemos hacer potencias entre arrays.

## Potencia

Como es normal, se basa en realizar la potencia entre los valores que comparten posición en los arrays:

In [ ]:
arr_1 ** arr_2

## Operaciones en arrays 2D

Todo lo que hemos visto aplica también a los arrays de dos dimensiones:

In [15]:
arr_5 = np.array([[1,2],[3,4]])
print(arr_5.ndim)

arr_6 = np.array([[5,6],[7,8]])

arr_5 + arr_6

2


AttributeError: 'numpy.ndarray' object has no attribute 'nshp'

Se realiza la operación entre los valores que comparten posición en los arrays:


`[[1+5, 2+6], [3+7, 4+8]] = [[6, 8], [10, 12]]`

De igual forma funcionaría el producto, división y potencia por un número:

In [ ]:
arr_5 * 3

`[[1x3, 2x3], [3x3, 4x3]] = [[3, 6], [9, 12]]`

Podemos multiplicar, dividir y potenciar matrices siempre que el número de columnas de la primera coincida con el número de reglones de la segunda:

In [ ]:
arr_5 * np.array([5,10])

Si esto no se cumple...

In [ ]:
arr_5 * np.array([5,10,15])