# Funciones aleatorias

Hablando de funciones no podemos olvidar las funciones aleatorias encontradas en el módulo `random`. [En la documentación oficial](https://numpy.org/doc/stable/reference/random/index.html) encontraréis el listado completo con ejemplos de uso.

Tenemos funciones para generar arrays con `datos aleatorios` y `permutaciones`. También hay muchas enfocadas a generar muestras de distribuciones de probabilidad pensadas para visualizar estadística.

Vamos a practicar algunas de las dos primeras.

## Datos aleatorios

In [1]:
import numpy as np

In [2]:
# número decimal entre 0 y 1
np.random.rand()

0.7001446467849718

In [3]:
# array 1D de decimales entre 0 y 1
np.random.rand(4)

array([0.59839584, 0.40749021, 0.61450275, 0.80744229])

In [7]:
# array 2D de decimales entre 0 y 1
np.random.rand(4,2)

array([[0.78421839, 0.77669356],
       [0.16862773, 0.01783998],
       [0.96756095, 0.09988016],
       [0.9973974 , 0.94581418]])

In [9]:
# array 3D de decimales entre 0 y N
np.random.uniform(10, size=[2,2,2])

array([[[6.74079333, 5.43391932],
        [3.78387981, 6.7686508 ]],

       [[1.70875207, 4.47472   ],
        [4.65142823, 9.32173138]]])

In [10]:
# array 4D de decimales entre -N y M
np.random.uniform(-10, 10, size=[2,2,2,2])

array([[[[-6.58040021, -8.03041176],
         [ 4.40921318,  8.64168613]],

        [[ 5.45375076, -7.87953686],
         [ 7.79724962,  5.91868384]]],


       [[[-9.26590067,  7.6253674 ],
         [ 2.63900002,  0.59676577]],

        [[ 6.40511678,  6.25973656],
         [ 7.40025488, -1.05690769]]]])

In [5]:
# número entero entre 0 y N
np.random.randint(1,100 size=10)

4

In [6]:
# array de enteros entre 0 y N
np.random.randint(10, size=[3,2])

array([[2, 9],
       [6, 1],
       [1, 3]])

In [8]:
# array de enteros entre -N y M
np.random.randint(-10, 10, size=[3,2])

array([[ 2,  0],
       [ 6, -3],
       [ 4, -1]])

In [ ]:
# array uniforme con curva gaussiana
np.random.normal(size=20)

## Permutaciones

In [ ]:
arr = np.arange(10)

arr

In [ ]:
# desordenar un array
np.random.shuffle(arr)

arr

In [ ]:
# generar secuencia permutada a partir de un número
np.random.permutation(15)