# Creación de Arrays

### Crear un array a partir de una lista

In [3]:
import numpy as np



### Crear un array de ceros de tamaño 5x5

In [6]:
#Código crear un array de ceros de tamaño 5x5

array_1 = np.zeros([5,5])
print(array_1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Crear un array de unos de tamaño 3x3

In [7]:
#Código crear un array de unos de tamaño 3x3
array_2 = np.ones([3,3])
print(array_2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Crear un array con valores espaciados uniformemente de 0 a 9

In [10]:
#Código rear un array con valores espaciados uniformemente de 0 a 9
array_3 = np.arange(10)
print(array_3)

[0 1 2 3 4 5 6 7 8 9]


### #Crear un array con 6 valores espaciados linealmente entre 0 y 1


In [11]:
#Código crear un array con 6 valores espaciados linealmente entre 0 y 1
array_4 = np.arange(0,1, step = 0.2)
print(array_4)


[0.  0.2 0.4 0.6 0.8]


# Operaciones Básicas

### Realizar una suma, resta, multiplicación y división entre dos arrays

In [13]:
array_1 = np.array([5,4,2])
array_2 = np.array([6,4,9])

#Código realizar una suma, resta, multiplicación y división entre dos arrays

array_suma = array_1 + array_2
print("El resultado de la suma es:",array_suma)

array_prod = array_1 * array_2
print("El resultado del producto es:", array_prod)

array_resta = array_1 - array_2
print("El resultado de la resta es:", array_resta)

array_div = array_1 / array_2
print("El resultado de la división es:", array_div)



# Salida
'''
print("La suma es: ",suma)
print("La resta es: ",resta)
print("La multiplicacion es: ",multiplicacion)
print("La division es: ",division)
'''


[11  8 11]
[30 16 18]
[-1  0 -7]
[0.83333333 1.         0.22222222]


'\nprint("La suma es: ",suma)\nprint("La resta es: ",resta)\nprint("La multiplicacion es: ",multiplicacion)\nprint("La division es: ",division)\n'

In [14]:
#Calcular el producto punto de dos arrays
array_1 =np.array([2,4,8])
array_2 = np.array([-4,7,10 ])

resultado = np.dot(array_1,array_2)
print(resultado)

100


In [17]:
#Transponer un array

print("vamos a trasnponer este array")

array_1 = np.array(([14,5,9], [11,25,33], [10,-5,4]))

print(array_1)

array_1transp = array_1.T
print(array_1transp)





vamos a trasnponer este array
[[14  5  9]
 [11 25 33]
 [10 -5  4]]
[[14 11 10]
 [ 5 25 -5]
 [ 9 33  4]]


# Operaciones Estadísticas

In [22]:
#Calcular la media, suma, valor mínimo y valor máximo de un array

# Crear un array NumPy
array_numeros = np.array([5, 2, 4, 1, 3])

# Calcular la media

array_media = array_numeros.mean()

print("La media tiene un valor de", array_media)

# Calcular la suma

array_suma = array_numeros.sum()
print("El resultado de la suma de los elementos es:",array_suma)

# Calcular el valor mínimo

min = array_numeros.min()
print("El valor minimo de los elementos es:", min)
# Calcular el valor máximo

max = array_numeros.max()

print("El valor máximo de los elementos es:",max)
'''
# Mostrar los resultados
print("La media es:", media)
print("La suma es:", suma)
print("El valor mínimo es:", valor_minimo)
print("El valor máximo es:", valor_maximo)
'''


3.0
15
1
5


'\n# Mostrar los resultados\nprint("La media es:", media)\nprint("La suma es:", suma)\nprint("El valor mínimo es:", valor_minimo)\nprint("El valor máximo es:", valor_maximo)\n'

In [75]:
#Cambiar la forma de un array "reshape"


# Crear un array original
array_original = np.array([1, 2, 3, 4, 5, 6])

# Nueva forma deseada (2 filas y 3 columnas)
array_cambiado = array_original.reshape(2,3)

print(array_cambiado)

'''
# Imprimir el array original y el reshapeado
print("Array original:", array_original)
print("Array reshapeado:", array_reshapeado)
'''

[[1 2 3]
 [4 5 6]]


'\n# Imprimir el array original y el reshapeado\nprint("Array original:", array_original)\nprint("Array reshapeado:", array_reshapeado)\n'

# Álgebra Lineal

### Calcular el determinante de una matriz 2x2

In [25]:
nuevo_array = np.array([[1,2],[2,5]])

#Código para calcular el determinante de una matriz 2x2

print("vamos a calcular el valor del determinante de", nuevo_array)

determinante = np.linalg.det(nuevo_array)
print("El determinante de", nuevo_array, "es", determinante)

#print(determinante)

vamos a calcular el valor del determinante de [[1 2]
 [2 5]]
El determinante de [[1 2]
 [2 5]] es 1.0


### Calcular la matriz inversa de una matriz 3x3

In [27]:
# Definir la matriz 3x3
nuevo_array = np.array(([4,7,22], [5,8,19], [11,7,20]))
print("La matriz es", nuevo_array)

# Calcular la matriz inversa
inversa = np.linalg.inv(nuevo_array)

# Imprimir la matriz inversa
print("la matriz origina es", nuevo_array,"Su inversa es", inversa)


La matriz es [[ 4  7 22]
 [ 5  8 19]
 [11  7 20]]
la matriz origina es [[ 4  7 22]
 [ 5  8 19]
 [11  7 20]] Su inversa es [[-0.09152542 -0.04745763  0.14576271]
 [-0.36949153  0.54915254 -0.11525424]
 [ 0.17966102 -0.16610169  0.01016949]]


### Calcular los valores propios y vectores propios de una matriz 4x4

In [29]:

# Definir la matriz 4x4
matriz_4x4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

# Calcular valores propios y vectores propios
valores, vectores = np.linalg.eig(matriz_4x4)
valores
vectores


# Separar valores propios y vectores propios
 # Parte real de los valores propios complejos
  # Parte real de los vectores propios complejos

# Imprimir resultados
'''
print("Valores propios:", autovalores)
print("Vectores propios:")
for i in range(len(autovectores)):
    print(f"Vector propio {i+1}:", autovectores[i])
'''

'\nprint("Valores propios:", autovalores)\nprint("Vectores propios:")\nfor i in range(len(autovectores)):\n    print(f"Vector propio {i+1}:", autovectores[i])\n'

# Funciones Universales

In [33]:
# Crear un array con ángulos
array_angulos = np.array([0, np.pi/2, np.pi])
array_angulos2 = np.array([1, np.pi/2, np.pi])

# Calcular el seno de los ángulos

res_sen = np.sin(array_angulos)

print("los valores del sen de cada angulo son", res_sen)
# Calcular el coseno de los ángulos

res_cos = np.cos(array_angulos)

print("el valor del coseno de cada angulo es", res_cos)

# Calcular la exponencial de los ángulos

res_exp = np.exp(array_angulos)
print(res_exp)

# Calcular el logaritmo natural de los ángulos

res_ln = np.log(array_angulos2)
print (res_ln)


los valores del sen de cada angulo son [0.0000000e+00 1.0000000e+00 1.2246468e-16]
el valor del coseno de cada angulo es [ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 1.          4.81047738 23.14069263]
[0.         0.45158271 1.14472989]


In [44]:
#Realizar indexación y slicing en un array 2D
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(array_2d)


# Obtener la primera fila del array

fila_1 = array_2d[0][:]

print(fila_1)

# Obtener la última columna del array
  # [3, 6, 9]
columna_final = array_2d[:][2]
  
print(columna_final)

# Obtener una submatriz que contiene la segunda fila y las dos primeras columnas
  # [4, 5]

sub_mat = array_2d[1][:]
print(sub_mat)

col = array_2d[:][0:2]

print(col)
# Imprimir los subconjuntos de datos extraídos


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[7 8 9]
[4 5 6]
[[1 2 3]
 [4 5 6]]


# Generación de Números Aleatorios

In [48]:
#Generar un array de 10 números enteros aleatorios entre 1 y 100
aleatorio = np.random.randint(1,100, size=10)
print(aleatorio)

[86 75 59 58 87 43 85 17 10 74]


In [74]:
#Generar una matriz 2x3 con números aleatorios uniformemente distribuidos entre 0 y 1
matriz_ale = np.random.uniform(0,1, size = (2,3))
print(matriz_ale)

[[0.08449622 0.47681125 0.809296  ]
 [0.88919187 0.69668039 0.96771117]]


In [71]:
#Generar un array de 5 números aleatorios con distribución normal (media 0, desviación estándar 1)

array = np.random.normal(size=5)
print(array)

[-0.03258485  0.92775482  1.18872942 -1.96248195  0.63666896]
