# La clase array de NumPy

La programación gráfica se basa en la idea de manipular información almacenada en unas estructuras conocidas como vectores y matrices. 

En Python la única forma de simular estas estructuras es usando listas y lo malo es que son muy limitadas respecto a las funciones matemáticas que permiten. 

**Numpy** viene a solucionar esa carencia ofreciéndonos un nuevo tipo de dato llamado `array`, es parecido a una lista y de hecho se puede crear a partir de ellas:

In [1]:
# Normalmente se suele importar numpy como np
import numpy as np

# Podemos crear un arreglo a partir de
array = np.array([1, 2, 3, 4, 5])

# Y lo mostramos
array

array([1, 2, 3, 4, 5])

Si lo imprimimos directamente notaremos algo interesante:

In [2]:
print(array)

[1 2 3 4 5]


En la representación en forma de cadena, son como listas pero con los elementos separados por espacios.

Podemos consultar el tipo de la variable:

In [3]:
type(array)

numpy.ndarray

Este `array` formado a partir de una lista simple tiene una dimensión y se conoce como **vector**.

## Dimensión y forma

Podemos consultar la dimensión y forma de un `array` con sus propiedades `ndim` y `shape`:

In [4]:
array.ndim

1

In [5]:
array.shape

(5,)

En la tupla `(5,)` el primer valor indica a que el array tiene 5 elementos en la primera dimensión (de ancho).

Ahora bien, si definimos un `array` a partir de una lista anidada formada por dos sublistas:

In [6]:
array = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
])

In [7]:
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [8]:
array.ndim

2

In [9]:
array.shape

(2, 5)

En este caso `array` se muestra como una tabla de 2 filas y 5 columnas, números que precisamente concuerdan con la forma `(2, 5)`.

Estas estructuras formadas por filas y columnas parecidas a una tabla tienen dos dimensiones, ancho y alto. 

También se conocen como vectores multidimensionales o matrices 2D.

## Tipo de datos

Podemos consultar el tipo de un `array`, por ejemplo éste que contiene sólo enteros:

In [10]:
array = np.array([1, 2, 3, 4, 5])

In [11]:
array.dtype

dtype('int32')

En mi máquina el tipo del `array` se establece automáticamente como `int64` (entero de 64 bits), aunque puede diferir dependiendo de la arquitectura del procesador.

Si uno de los valores fuera decimal el tipo del `array` completo cambiará a decimal:

In [12]:
array = np.array([1, 2, 3, 4, 5, 6.1234])

In [13]:
array.dtype

dtype('float64')

También podemos almacenar cadenas:

In [14]:
array = np.array(["Hola", "que", "tal"])

In [15]:
array.dtype

dtype('<U4')

En este caso nos indica un tipo extraño llamado `<U4`. Según la documentación de numpy esto hace referencia a que el `array` es de tipo `Unicode`, es decir, que contiene símbolos de escritura.

Si mezclamos números y textos el tipo cambia un poco más:

In [16]:
array = np.array(["Hola", 1234, 3.1415])

In [17]:
array.dtype

dtype('<U32')

Si mostramos su contenido veremos algo interesante:

In [18]:
array

array(['Hola', '1234', '3.1415'], dtype='<U32')

Todo se han vuelto cadenas de caracteres.

Con esto queda claro que los `arrays` no son listas, sino unas estructuras pensadas para almacenar vectores y matrices, que son conscientes en todo momento de su dimensión, forma y tipo de datos.

## Tablas y gráficos - Manos a la obra

Podemos mostrar gráficos y tablas, para ello se utiliza las biblioteca `numpy` en conjunto con `matplotlib` y `pandas`.

Ambas las veremos en profundidad en las próximas secciones, pero vamos a hacer un ejemplo:

In [27]:
#Escriba el código

import numpy as np
import pandas as pd

tabla = pd.DataFrame(
    np.random.randint(50,100, size=(4,3)),
    columns=['Daniela','Luis','Karol']
)
tabla

Daniela  Luis  Karol
0       81    50     57
1       60    62     54
2       51    63     54
3       99    69     59

En este fragmente estamos haciendo uso de los `dataframes` de `pandas` para manejar una tabla generada a partir de un `array` con valores aleatorios.

¿Véis lo que os decía sobre cómo se complementan entre ellas?

Con los gráficos pasa lo mismo, podemos dibujar la tabla usando `matplotlib` completando así el ciclo del análisis:

In [24]:
#Escriba el código

import matplotlib.pyplot as plt

tabla.plot()
plt.show()



NameError: name 'tabla' is not defined

La función `show()` causa que la figura se dibuje en la propia celda de entrada `In`.



Utilizando la intrucción especial de Jupyter Notebook `%matplotlib inline` podemos hacer que un gráfico se dibuje en la celda de salida `Out`, esto nos permitirá dibujar más de un gráfico, sería lo equivalente a utilizar `print()` múltiples veces:

In [ ]:
%matplotlib inline
tabla.plot()
tabla.plot()
tabla.plot()

Pero no nos adelantemos, hablaremos más sobre gráficos en la sección de `matplotlib`.