# Arrays pregenerados

Crear arrays a partir de listas puede ser muy tedioso, por eso `numpy` integra varias funciones muy útiles para generar arrays de uso común en el álgebra de matrices.

## Array de ceros

Un array de ceros es cuando todos sus elementos son ceros. Podemos generarlos con el método `zeros`:

In [3]:
import numpy as np
np.zeros(3)

array([0., 0., 0.])


Evidentemente podemos generar arrays multidimensionales, pero para ello tenemos que pasarle al método una lista o tupla con la longitud de sus dimensiones:

In [4]:
#Escriba el código
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Array de unos

Lo mismo podemos hacer pero utilizando el método `ones`:

In [5]:
np.ones([3,3])
type(np.ones([3,3]))
np.ones([3,3]).dtype

dtype('float64')

## Array de identidad

Los arrays de identidad son matrices cuadradas (con el mismo número de filas que de columnas) donde todos los valores son ceros a excepción de la diagonal donde son unos. Podemos generarlos con el método `eye`:

In [11]:
np.arange(0,20,5)


TypeError: argument for arange() given by name ('start') and position (position 0)

: 

De forma similar a como multiplicar un número por 1 da como resulta el mismo número, multiplicar una matriz por su matriz de identidad da como resultado la matriz original. Eso tiene muchas aplicaciones en el álgrebra de matrices, especialmente en el renderizado de gráficos.

## Array de rangos

Por último pero no por ello menos importante también es posible generar arrays a partir de un rango de valores. Para hacerlo utilizaríamos el método `arange`:


In [6]:
# Rango de 0 a 4
np.arange(4)

array([0, 1, 2, 3])

In [7]:
# Rango 0 a 4 decimal
np.arange(4.)

array([0., 1., 2., 3.])

### Practica

In [8]:
# Rango de -3 a 4  - Escriba el código
np.arange(-3,5)

array([-3, -2, -1,  0,  1,  2,  3,  4])

In [ ]:
# Rango de 20 números a partir de 0 cada 5 números - Escriba el código
np.arange(0,19)