# Funciones aleatorias

Hablando de funciones no podemos olvidar las funciones aleatorias encontradas en el módulo `random`. [En la documentación oficial](https://numpy.org/doc/stable/reference/random/index.html) encontraréis el listado completo con ejemplos de uso.

Tenemos funciones para generar arrays con `datos aleatorios` y `permutaciones`. También hay muchas enfocadas a generar muestras de distribuciones de probabilidad pensadas para visualizar estadística.

Vamos a practicar algunas de las dos primeras.

## Datos aleatorios

In [1]:
import numpy as np

In [2]:
# número decimal entre 0 y 1
np.random.rand()

0.386648963495826

In [3]:
# array 1D de decimales entre 0 y 1
np.random.rand(4)

array([0.21069996, 0.90735534, 0.18631291, 0.36536254])

In [4]:
# array 2D de decimales entre 0 y 1
np.random.rand(4,2)

array([[0.62073849, 0.76188441],
       [0.97475324, 0.76761327],
       [0.00917097, 0.70572427],
       [0.38306421, 0.6895011 ]])

In [5]:
# array 3D de decimales entre 0 y N
np.random.uniform(10, size=[2,2,2])

array([[[1.43558876, 2.52593843],
        [8.6859797 , 3.28110299]],

       [[7.92973863, 7.42356721],
        [4.5692619 , 2.22872698]]])

In [6]:
# array 4D de decimales entre -N y M
np.random.uniform(-10, 10, size=[2,2,2,2])

array([[[[-8.91587241, -9.14136415],
         [ 3.90590641,  3.52546199]],

        [[-6.95883622, -5.39336796],
         [-2.76960556, -0.0969801 ]]],


       [[[-2.83721269,  9.61953221],
         [-5.44760969,  8.39507268]],

        [[ 0.40778803,  8.4621483 ],
         [ 5.44602109,  4.72579684]]]])

In [7]:
# número entero entre 0 y N
np.random.randint(10)

4

In [8]:
# array de enteros entre 0 y N
np.random.randint(10, size=[3,2])

array([[3, 5],
       [1, 4],
       [5, 9]])

In [9]:
# array de enteros entre -N y M
np.random.randint(-10, 10, size=[3,2])

array([[ 6,  2],
       [-3, -9],
       [-9,  8]])

In [10]:
# array uniforme con curva gaussiana
np.random.normal(size=20)

array([-1.30755526,  1.35796201,  1.58245591,  0.68059318, -1.0267236 ,
       -0.02381586, -0.798664  , -1.69139702, -0.20769366, -0.78508742,
       -0.20758288,  1.65117752,  0.20587557, -1.19371601,  1.04740106,
        0.72496627,  0.9056635 ,  0.72754208,  0.27353168, -0.36419631])

## Permutaciones

In [11]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# desordenar un array
np.random.shuffle(arr)

arr

array([4, 6, 9, 8, 1, 5, 0, 7, 2, 3])

In [13]:
# generar secuencia permutada a partir de un número
np.random.permutation(15)

array([ 1,  0, 11,  5, 13,  3,  7,  4,  2, 12, 14,  6, 10,  8,  9])