# Creación de Arrays

### Crear un array a partir de una lista

In [5]:
import numpy as np



### Crear un array de ceros de tamaño 5x5

In [6]:
#Código crear un array de ceros de tamaño 5x5

array = np.zeros ((5, 5))
array



array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Crear un array de unos de tamaño 3x3

In [7]:
#Código crear un array de unos de tamaño 3x3

array1 = np.ones ((3, 3))
array1


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Crear un array con valores espaciados uniformemente de 0 a 9

In [11]:
#Código rear un array con valores espaciados uniformemente de 0 a 9
array2 = np.arange(0, 9., 0.5)
print(array2)


[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5]


### #Crear un array con 6 valores espaciados linealmente entre 0 y 1


In [12]:
#Código crear un array con 6 valores espaciados linealmente entre 0 y 1
array3 = np.arange(0, 1., 0.15)
print(array3)

[0.   0.15 0.3  0.45 0.6  0.75 0.9 ]


# Operaciones Básicas

### Realizar una suma, resta, multiplicación y división entre dos arrays

In [13]:
array_1 = np.array([5,4,2])
array_2 = np.array([6,4,9])


#Código realizar una suma, resta, multiplicación y división entre dos arrays
suma = array_1 + array_2
resta = array_1 - array_2
multiplicacion = array_1 * array_2
division = array_1 / array_2

#Salida
print('La suma es: ' ,suma)
print("La resta es: " ,resta)
print("La multiplicacion es: " ,multiplicacion)
print("La division es: " ,division)




# Salida
'''
print("La suma es: ",suma)
print("La resta es: ",resta)
print("La multiplicacion es: ",multiplicacion)
print("La division es: ",division)
'''

La suma es:  [11  8 11]
La resta es:  [-1  0 -7]
La multiplicacion es:  [30 16 18]
La division es:  [0.83333333 1.         0.22222222]


'\nprint("La suma es: ",suma)\nprint("La resta es: ",resta)\nprint("La multiplicacion es: ",multiplicacion)\nprint("La division es: ",division)\n'

In [14]:
#Calcular el producto punto de dos arrays

pdpto = np.dot(array_1, array_2)
print(pdpto)

64


In [33]:
#Transponer un array
arr = np.array([array_1,array_2])
arr

array([[5, 4, 2],
       [6, 4, 9]])

# Operaciones Estadísticas

In [15]:
#Calcular la media, suma, valor mínimo y valor máximo de un array


# Crear un array NumPy
array_numeros = np.array([5, 2, 4, 1, 3])

# Calcular la media
media = array_numeros.mean()

# Calcular la suma
suma = array_numeros.sum()
           
#Calcular el valor mínimo
valor_minimo = array_numeros.min()

# Calcular el valor máximo
valor_maximo = array_numeros.max()

print("La media es:", media)
print("La suma es:", suma)
print("El valor mínimo es:", valor_minimo)
print("El valor máximo es:", valor_maximo)

'''
# Mostrar los resultados
print("La media es:", media)
print("La suma es:", suma)
print("El valor mínimo es:", valor_minimo)
print("El valor máximo es:", valor_maximo)
'''


La media es: 3.0
La suma es: 15
El valor mínimo es: 1
El valor máximo es: 5


'\n# Mostrar los resultados\nprint("La media es:", media)\nprint("La suma es:", suma)\nprint("El valor mínimo es:", valor_minimo)\nprint("El valor máximo es:", valor_maximo)\n'

In [16]:
#Cambiar la forma de un array "reshape"


# Crear un array original
array_original = np.array([1, 2, 3, 4, 5, 6])

# Nueva forma deseada (2 filas y 3 columnas)
array_reshapeado = array_original.reshape(2, 3)
print("Array original:", array_original)
print("Array reshapeado:", array_reshapeado)

'''
# Imprimir el array original y el reshapeado
print("Array original:", array_original)
print("Array reshapeado:", array_reshapeado)
'''

Array original: [1 2 3 4 5 6]
Array reshapeado: [[1 2 3]
 [4 5 6]]


'\n# Imprimir el array original y el reshapeado\nprint("Array original:", array_original)\nprint("Array reshapeado:", array_reshapeado)\n'

# Álgebra Lineal

### Calcular el determinante de una matriz 2x2

In [17]:
nuevo_array = np.array([[1,2],[2,5]])

#Código para calcular el determinante de una matriz 2x2
determinante =np.linalg.det(nuevo_array)
print(determinante)

1.0


### Calcular la matriz inversa de una matriz 3x3

In [18]:
# Definir la matriz 3x3
matriz = np.array(([5, 10, 15], [20, 25, 30], [35, 40, 45]))
print(matriz)

# Calcular la matriz inversa
matriz_inversa = np.linalg.inv(matriz)

# Imprimir la matriz inversa
print(matriz_inversa)


[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
[[ 1.40737488e+14 -2.81474977e+14  1.40737488e+14]
 [-2.81474977e+14  5.62949953e+14 -2.81474977e+14]
 [ 1.40737488e+14 -2.81474977e+14  1.40737488e+14]]


### Calcular los valores propios y vectores propios de una matriz 4x4

In [19]:

# Definir la matriz 4x4
matriz_4x4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print (matriz_4x4)

# Calcular valores propios y vectores propios
autovalores, autovectores = np.linalg.eig(matriz_4x4)

# Separar valores propios y vectores propios
 # Parte real de los valores propios complejos
  # Parte real de los vectores propios complejos

# Imprimir resultados
print("Valores propios:", autovalores)
print("Vectores propios:")
for i in range(len(autovectores)):
    print(f"Vector propio {i+1}:", autovectores[i])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Valores propios: [ 3.62093727e+01 -2.20937271e+00 -5.14138333e-16 -2.08943529e-15]
Vectores propios:
Vector propio 1: [-0.15115432 -0.72704996  0.01790738 -0.26832672]
Vector propio 2: [-0.34923733 -0.28320876  0.38415354  0.71367217]
Vector propio 3: [-0.54732033  0.16063243 -0.82202921 -0.62236419]
Vector propio 4: [-0.74540333  0.60447363  0.41996829  0.17701873]


# Funciones Universales

In [21]:
# Crear un array con ángulos
array_angulos = np.array([1, np.pi/2, np.pi])

# Calcular el seno de los ángulos
print(np.sin(array_angulos))

# Calcular el coseno de los ángulos
print(np.cos(array_angulos))

# Calcular la exponencial de los ángulos

print(np.exp(array_angulos))

# Calcular el logaritmo natural de los ángulos

print(np.log(array_angulos))


[8.41470985e-01 1.00000000e+00 1.22464680e-16]
[ 5.40302306e-01  6.12323400e-17 -1.00000000e+00]
[ 2.71828183  4.81047738 23.14069263]
[0.         0.45158271 1.14472989]


In [22]:
#Realizar indexación y slicing en un array 2D
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_2d)

# Obtener la primera fila del array
fila1 = array_2d[0]

# Obtener la última columna del array
  # [3, 6, 9]
columna = array_2d[-1]

# Obtener una submatriz que contiene la segunda fila y las dos primeras columnas
  # [4, 5]
submatriz = array_2d[1, :2]

# Imprimir los subconjuntos de datos extraídos
print('primera fila = ', fila1)
print('columna = ', columna)
print('submatriz = ', submatriz)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
primera fila =  [1 2 3]
columna =  [7 8 9]
submatriz =  [4 5]


# Generación de Números Aleatorios

In [25]:
#Generar un array de 10 números enteros aleatorios entre 1 y 100

aleatorio = np.random.randint(1, 100, 10)
print(aleatorio)


[92 60 86 96 48 98 68 40 99 95]


In [26]:
#Generar una matriz 2x3 con números aleatorios uniformemente distribuidos entre 0 y 1
al_unif = np.random.rand(2, 3)
print(al_unif)

[[0.59849472 0.16430528 0.42407337]
 [0.13569743 0.09125976 0.7253847 ]]


In [27]:
#Generar un array de 5 números aleatorios con distribución normal (media 0, desviación estándar 1)

al_normal = np.random.normal(0, 1, 5)
print(al_normal)

[-1.50378051 -0.99601672  0.01850888 -0.52707642 -2.1423117 ]
