# Creación de Arrays

### Crear un array a partir de una lista

In [2]:
import numpy as np


### Crear un array de ceros de tamaño 5x5

In [ ]:
#Código crear un array de ceros de tamaño 5x5

a = np.zeros([5, 5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Crear un array de unos de tamaño 3x3

In [ ]:
#Código crear un array de unos de tamaño 3x3
a = np.ones([3, 3])
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Crear un array con valores espaciados uniformemente de 0 a 9

In [ ]:
#Código rear un array con valores espaciados uniformemente de 0 a 9
a = np.arange(0, 9.5, 0.5)
print(a)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9. ]


### #Crear un array con 6 valores espaciados linealmente entre 0 y 1


In [ ]:
#Código crear un array con 6 valores espaciados linealmente entre 0 y 1
a = np.arange(0, 1.2, 0.2)
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


# Operaciones Básicas

### Realizar una suma, resta, multiplicación y división entre dos arrays

In [ ]:
array_1 = np.array([5,4,2])
array_2 = np.array([6,4,9])

#Código realizar una suma, resta, multiplicación y división entre dos arrays

suma = array_1 + array_2
resta = array_1 - array_2
multiplicacion = array_1 * array_2
division = array_1 / array_2

# Salida

print("La suma es: ",suma)
print("La resta es: ",resta)
print("La multiplicacion es: ",multiplicacion)
print("La division es: ",division)


La suma es:  [11  8 11]
La resta es:  [-1  0 -7]
La multiplicacion es:  [30 16 18]
La division es:  [0.83333333 1.         0.22222222]


In [ ]:
#Calcular el producto punto de dos arrays
pp = np.dot(array_1, array_2)
print(pp)

64


In [ ]:
#Transponer un array

a = np.array([[1, 2, 3]])
print(a)
t = a.transpose()
print(t)


[[1 2 3]]
[[1]
 [2]
 [3]]


# Operaciones Estadísticas

In [ ]:
#Calcular la media, suma, valor mínimo y valor máximo de un array


# Crear un array NumPy
array_numeros = np.array([5, 2, 4, 1, 3])

# Calcular la media
media = array_numeros.mean()

# Calcular la suma
suma = array_numeros.sum()

# Calcular el valor mínimo
valor_minimo = array_numeros.min()

# Calcular el valor máximo
valor_maximo = array_numeros.max()


# Mostrar los resultados
print("La media es:", media)
print("La suma es:", suma)
print("El valor mínimo es:", valor_minimo)
print("El valor máximo es:", valor_maximo)



La media es: 3.0
La suma es: 15
El valor mínimo es: 1
El valor máximo es: 5


In [ ]:
#Cambiar la forma de un array "reshape"


# Crear un array original
array_original = np.array([1, 2, 3, 4, 5, 6])

# Nueva forma deseada (2 filas y 3 columnas)
array_reshapeado = array_original.reshape(2, 3)


# Imprimir el array original y el reshapeado
print("Array original:", array_original)
print("Array reshapeado:", array_reshapeado)


Array original: [1 2 3 4 5 6]
Array reshapeado: [[1 2 3]
 [4 5 6]]


# Álgebra Lineal

### Calcular el determinante de una matriz 2x2

In [ ]:
nuevo_array = np.array([[1,2],[2,5]])
print(nuevo_array)
#Código para calcular el determinante de una matriz 2x2
determinante = np.linalg.det(nuevo_array)
print(determinante)

[[1 2]
 [2 5]]
1.0


### Calcular la matriz inversa de una matriz 3x3

In [ ]:
# Definir la matriz 3x3
a = np.array([[70, 80, 90], [4, 5, 6], [15, 25, 100]])
print(a)

# Calcular la matriz inversa
i = np.linalg.inv(a)

# Imprimir la matriz inversa
print(i)


[[ 70  80  90]
 [  4   5   6]
 [ 15  25 100]]
[[ 0.17948718 -2.94871795  0.01538462]
 [-0.15897436  2.8974359  -0.03076923]
 [ 0.01282051 -0.28205128  0.01538462]]


### Calcular los valores propios y vectores propios de una matriz 4x4

In [7]:
# Definir la matriz 4x4
matriz_4x4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print (matriz_4x4)

# Calcular valores propios y vectores propios
autovalores, autovectores = np.linalg.eig(matriz_4x4)

# Separar valores propios y vectores propios
 # Parte real de los valores propios complejos
  # Parte real de los vectores propios complejos

# Imprimir resultados
print("Valores propios:", autovalores)
print("Vectores propios:")
for i in range(len(autovectores)):
    print(f"Vector propio {i+1}:", autovectores[i])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Valores propios: [ 3.62093727e+01 -2.20937271e+00 -2.62410379e-15 -9.51420961e-17]
Vectores propios:
Vector propio 1: [-0.15115432 -0.72704996 -0.47688035 -0.07702174]
Vector propio 2: [-0.34923733 -0.28320876  0.83665151 -0.30149603]
Vector propio 3: [-0.54732033  0.16063243 -0.24266197  0.83405728]
Vector propio 4: [-0.74540333  0.60447363 -0.11710919 -0.45553951]


# Funciones Universales

In [12]:
# Crear un array con ángulos
array_angulos = np.array([0.001, np.pi/2, np.pi])

# Calcular el seno de los ángulos
print(np.sin(array_angulos))

# Calcular el coseno de los ángulos
print(np.cos(array_angulos))

# Calcular la exponencial de los ángulos
print(np.exp(array_angulos))

# Calcular el logaritmo natural de los ángulos
print(np.log(array_angulos))


[9.99999833e-04 1.00000000e+00 1.22464680e-16]
[ 9.999995e-01  6.123234e-17 -1.000000e+00]
[ 1.0010005   4.81047738 23.14069263]
[-6.90775528  0.45158271  1.14472989]


In [45]:
#Realizar indexación y slicing en un array 2D
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('array_2d = ')
print(array_2d)

# Obtener la primera fila del array
a = array_2d[0]

# Obtener la última columna del array
  # [3, 6, 9]
b = array_2d[:3, 2]

# Obtener una submatriz que contiene la segunda fila y las dos primeras columnas
  # [4, 5]
c = array_2d[1, :2]

# Imprimir los subconjuntos de datos extraídos
print('a = ', a)
print('b = ', b)
print('c = ', c)

array_2d = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
a =  [1 2 3]
b =  [3 6 9]
c =  [4 5]


# Generación de Números Aleatorios

In [62]:
#Generar un array de 10 números enteros aleatorios entre 1 y 100
a = np.random.randint(1, 100, 10)
print(a)


[45  6 21 52 66 67 58 75 12 12]


In [63]:
#Generar una matriz 2x3 con números aleatorios uniformemente distribuidos entre 0 y 1
a = np.random.rand(2, 3)
print(a)

[[0.46728771 0.28171636 0.11250772]
 [0.96921427 0.60322588 0.2625489 ]]


In [65]:
#Generar un array de 5 números aleatorios con distribución normal (media 0, desviación estándar 1)

a = np.random.normal(0, 1, 5)
print(a)

[ 0.7352472  -0.23177268  0.90730821 -0.23269236 -0.59490186]
