# Creación de Arrays

### Crear un array a partir de una lista

In [21]:
import numpy as np



### Crear un array de ceros de tamaño 5x5

In [22]:
#Código crear un array de ceros de tamaño 5x5

array = np.zeros ((5, 5))
array



array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Crear un array de unos de tamaño 3x3

In [24]:
#Código crear un array de unos de tamaño 3x3

array1 = np.ones ((3, 3))
array1


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Crear un array con valores espaciados uniformemente de 0 a 9

In [25]:
#Código rear un array con valores espaciados uniformemente de 0 a 9
array2 = np.arange (10)
array2


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### #Crear un array con 6 valores espaciados linealmente entre 0 y 1


In [26]:
#Código crear un array con 6 valores espaciados linealmente entre 0 y 1
array3 =np.random.rand(6)
array3

array([0.45598895, 0.45289376, 0.88269915, 0.04008005, 0.43446883,
       0.14124846])

# Operaciones Básicas

### Realizar una suma, resta, multiplicación y división entre dos arrays

In [27]:
array_1 = np.array([5,4,2])
array_2 = np.array([6,4,9])


#Código realizar una suma, resta, multiplicación y división entre dos arrays
suma = (array_1 + array_2)
resta = (array_1 - array_2)
multiplicacion = (array_1 * array_2)
division = (array_1 / array_2)

print('La suma es: ' ,suma)
print("La resta es: " ,resta)
print("La multiplicacion es: " ,multiplicacion)
print("La division es: " ,division)




# Salida
'''
print("La suma es: ",suma)
print("La resta es: ",resta)
print("La multiplicacion es: ",multiplicacion)
print("La division es: ",division)
'''

TypeError: 'tuple' object is not callable

In [28]:
array_1 = np.array([5,4,2])
array_2 = np.array([6,4,9])
#SUMA

array_1 + array_2

print("La suma es: ", array)

TypeError: 'tuple' object is not callable

In [29]:
#RESTA
array_1 - array_2
print = ("La resta es: ", array)

In [30]:
#MULTIPLICACION
array_1 * array_2
print = ("La multiplicacion es: ", array)

In [31]:
#DIVISION
array_1 / array_2
print = ("La division es: ", array)

In [32]:
#Calcular el producto punto de dos arrays
array_1 ** array_2

array([15625,   256,   512])

In [33]:
#Transponer un array
arr = np.array([array_1,array_2])
arr

array([[5, 4, 2],
       [6, 4, 9]])

# Operaciones Estadísticas

In [37]:
#Calcular la media, suma, valor mínimo y valor máximo de un array


# Crear un array NumPy
array_numeros = np.array([5, 2, 4, 1, 3])

# Calcular la media
mean = array_numeros.mean()
print(mean)

# Calcular la suma
suma = array_numeros.sum()
           
#Calcular el valor mínimo
valor_minimo = array_numeros.min()

# Calcular el valor máximo
valor_maximo = array_numeros.max()

print("La media es:", mean)
print("La suma es:", suma)
print("El valor mínimo es:", valor_minimo)
print("El valor máximo es:", valor_maximo)

'''
# Mostrar los resultados
print("La media es:", media)
print("La suma es:", suma)
print("El valor mínimo es:", valor_minimo)
print("El valor máximo es:", valor_maximo)
'''


TypeError: 'tuple' object is not callable

In [38]:
#Cambiar la forma de un array "reshape"


# Crear un array original
array_original = np.array([1, 2, 3, 4, 5, 6])

# Nueva forma deseada (2 filas y 3 columnas)
array_reshapeado = np.arange(6).reshape(2,3)
print("Array original:", array_original)
print("Array reshapeado:", array_reshapeado)

'''
# Imprimir el array original y el reshapeado
print("Array original:", array_original)
print("Array reshapeado:", array_reshapeado)
'''

TypeError: 'tuple' object is not callable

# Álgebra Lineal

### Calcular el determinante de una matriz 2x2

In [39]:
nuevo_array = np.array([[1,2],[2,5]])

#Código para calcular el determinante de una matriz 2x2
determinante =np.linalg.det(nuevo_array)
print(determinante)

TypeError: 'tuple' object is not callable

### Calcular la matriz inversa de una matriz 3x3

In [45]:
# Definir la matriz 3x3
matriz = np.array(([5, 10, 15], [20, 25, 30], [35, 40, 45]))

# Calcular la matriz inversa
matriz_inversa = np.linalg.inv(matriz)

# Imprimir la matriz inversa
print(matriz_inversa)


TypeError: 'tuple' object is not callable

### Calcular los valores propios y vectores propios de una matriz 4x4

In [46]:

# Definir la matriz 4x4
matriz_4x4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

# Calcular valores propios y vectores propios


# Separar valores propios y vectores propios
 # Parte real de los valores propios complejos
  # Parte real de los vectores propios complejos

# Imprimir resultados
'''
print("Valores propios:", autovalores)
print("Vectores propios:")
for i in range(len(autovectores)):
    print(f"Vector propio {i+1}:", autovectores[i])
'''

'\nprint("Valores propios:", autovalores)\nprint("Vectores propios:")\nfor i in range(len(autovectores)):\n    print(f"Vector propio {i+1}:", autovectores[i])\n'

# Funciones Universales

In [117]:
# Crear un array con ángulos
array_angulos = np.array([1, np.pi/2, np.pi])

# Calcular el seno de los ángulos
np.sin(array_angulos)

# Calcular el coseno de los ángulos
np.cos(array_angulos)

# Calcular la exponencial de los ángulos

np.exp(array_angulos)

# Calcular el logaritmo natural de los ángulos

np.log(array_angulos)


array([0.        , 0.45158271, 1.14472989])

In [52]:
#Realizar indexación y slicing en un array 2D
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


# Obtener la primera fila del array
array_2d[0]

# Obtener la última columna del array
  # [3, 6, 9]
array_2d[-1]

# Obtener una submatriz que contiene la segunda fila y las dos primeras columnas
  # [4, 5]
array_2d[:,:]
array_2d[1:,:2]

# Imprimir los subconjuntos de datos extraídos


array([[4, 5],
       [7, 8]])

# Generación de Números Aleatorios

In [68]:
#Generar un array de 10 números enteros aleatorios entre 1 y 100

aleatorio = np.random.randint(1, 100, size=(10,1))


In [ ]:
#Generar una matriz 2x3 con números aleatorios uniformemente distribuidos entre 0 y 1


In [ ]:
#Generar un array de 5 números aleatorios con distribución normal (media 0, desviación estándar 1)

