# Funciones aleatorias

Hablando de funciones no podemos olvidar las funciones aleatorias encontradas en el módulo `random`. [En la documentación oficial](https://numpy.org/doc/stable/reference/random/index.html) encontraréis el listado completo con ejemplos de uso.

Tenemos funciones para generar arrays con `datos aleatorios` y `permutaciones`. También hay muchas enfocadas a generar muestras de distribuciones de probabilidad pensadas para visualizar estadística.

Vamos a practicar algunas de las dos primeras.

## Datos aleatorios

In [1]:
import numpy as np

In [2]:
# número decimal entre 0 y 1
np.random.rand()

0.8103399501996146

In [3]:
# array 1D de decimales entre 0 y 1
np.random.rand(4)

array([0.11398691, 0.74910907, 0.05194622, 0.13654888])

In [4]:
# array 2D de decimales entre 0 y 1
np.random.rand(4,2)

array([[0.85069397, 0.34849787],
       [0.31935214, 0.51682054],
       [0.05862809, 0.19494589],
       [0.65784235, 0.1173528 ]])

In [5]:
# array 3D de decimales entre 0 y N
np.random.uniform(10, size=[2,2,2])

array([[[3.47469079, 9.97134285],
        [3.63242547, 6.69445365]],

       [[6.89102067, 7.83547596],
        [3.3802504 , 4.2601686 ]]])

In [6]:
# array 4D de decimales entre -N y M
np.random.uniform(-10, 10, size=[2,2,2,2])

array([[[[ 9.01810689, -3.31242181],
         [-9.8164558 ,  8.08571208]],

        [[-7.1044032 ,  1.27305313],
         [-8.28564962,  5.37375579]]],


       [[[ 4.9924328 , -7.02187568],
         [-0.03801438,  9.7198462 ]],

        [[ 6.46895125,  4.27593729],
         [-2.06537792,  8.2119552 ]]]])

In [7]:
# número entero entre 0 y N
np.random.randint(10)

6

In [8]:
# array de enteros entre 0 y N
np.random.randint(10, size=[3,2])

array([[5, 3],
       [5, 4],
       [9, 7]])

In [9]:
# array de enteros entre -N y M
np.random.randint(-10, 10, size=[3,2])

array([[-3, -1],
       [ 2,  4],
       [ 4, -5]])

In [10]:
# array uniforme con curva gaussiana
np.random.normal(size=20)

array([ 0.59169116, -0.58787633,  0.44656329, -0.60455907,  0.8935112 ,
        1.8447873 ,  0.06669604, -0.81824932, -0.99465747,  0.80631958,
        0.01208384,  0.76053502,  0.23531869, -0.53833255,  0.57525013,
       -1.7734049 , -1.76738778, -0.87080377,  0.47212585,  1.40880723])

## Permutaciones

In [11]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# desordenar un array
np.random.shuffle(arr)

arr

array([1, 2, 6, 0, 5, 4, 7, 9, 3, 8])

In [13]:
# generar secuencia permutada a partir de un número
np.random.permutation(15)

array([11,  8, 10,  7,  0,  3,  1, 12,  4,  5,  9, 13,  2, 14,  6])