# Creación de Arrays

### Crear un array a partir de una lista

In [3]:
import numpy as np

lista = [1, 2, 3, 4, 5]

#Respuesta
lista

[1, 2, 3, 4, 5]

### Crear un array de ceros de tamaño 5x5

In [4]:
#Código crear un array de ceros de tamaño 5x5
arr_ceros = np.zeros((5,5))
arr_ceros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Crear un array de unos de tamaño 3x3

In [6]:
#Código crear un array de unos de tamaño 3x3
arr_unos = np.ones((3,3))
arr_unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Crear un array con valores espaciados uniformemente de 0 a 9

In [22]:
#Código rear un array con valores espaciados uniformemente de 0 a 9
arr = np.random.uniform(10, size=5)
arr

array([1.77592844, 3.98588993, 3.01817258, 6.22820258, 8.81730004])

### #Crear un array con 6 valores espaciados linealmente entre 0 y 1


In [16]:
#Código crear un array con 6 valores espaciados linealmente entre 0 y 1
arr = np.random.rand(6)
arr

array([0.6719481 , 0.68500229, 0.36329162, 0.85094984, 0.39627677,
       0.45024012])

# Operaciones Básicas

### Realizar una suma, resta, multiplicación y división entre dos arrays

In [10]:
array_1 = np.array([5,4,2])
array_2 = np.array([6,4,9])

#Código realizar una suma, resta, multiplicación y división entre dos arrays
suma = np.add(array_1,array_2)
resta = np.subtract(array_1,array_2)
multiplicacion = array_1 * array_2
division = array_1 / array_2

# Salida

print("La suma es: ",suma)
print("La resta es: ",resta)
print("La multiplicacion es: ",multiplicacion)
print("La division es: ",division)


La suma es:  [11  8 11]
La resta es:  [-1  0 -7]
La multiplicacion es:  [30 16 18]
La division es:  [0.83333333 1.         0.22222222]


In [ ]:
#Calcular el producto punto de dos arrays


In [ ]:
#Transponer un array


# Operaciones Estadísticas

In [ ]:
#Calcular la media, suma, valor mínimo y valor máximo de un array



In [ ]:
#Cambiar la forma de un array "reshape"


# Álgebra Lineal

### Calcular el determinante de una matriz 2x2

In [ ]:
nuevo_array = np.array([[1,2],[2,5]])

#Código para calcular el determinante de una matriz 2x2

#print(determinante)

### Calcular la matriz inversa de una matriz 3x3

In [ ]:
# Definir la matriz 3x3


# Calcular la matriz inversa


# Imprimir la matriz inversa



### Calcular los valores propios y vectores propios de una matriz 4x4

In [ ]:

# Definir la matriz 4x4
matriz_4x4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

# Calcular valores propios y vectores propios


# Separar valores propios y vectores propios
 # Parte real de los valores propios complejos
  # Parte real de los vectores propios complejos

# Imprimir resultados
'''
print("Valores propios:", autovalores)
print("Vectores propios:")
for i in range(len(autovectores)):
    print(f"Vector propio {i+1}:", autovectores[i])
'''

# Funciones Universales

In [ ]:
# Crear un array con ángulos
array_angulos = np.array([0, np.pi/2, np.pi])

# Calcular el seno de los ángulos


# Calcular el coseno de los ángulos


# Calcular la exponencial de los ángulos


# Calcular el logaritmo natural de los ángulos




In [ ]:
#Realizar indexación y slicing en un array 2D
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Crear un array NumPy bidimensional


# Obtener la primera fila del array


# Obtener la última columna del array
  # [3, 6, 9]

# Obtener una submatriz que contiene la segunda fila y las dos primeras columnas
  # [4, 5]

# Imprimir los subconjuntos de datos extraídos


# Generación de Números Aleatorios

In [ ]:
#Generar un array de 10 números enteros aleatorios entre 1 y 100


In [ ]:
#Generar una matriz 2x3 con números aleatorios uniformemente distribuidos entre 0 y 1


In [ ]:
#Generar un array de 5 números aleatorios con distribución normal (media 0, desviación estándar 1)

