# Creación de Arrays

### Crear un array a partir de una lista

In [2]:
import numpy as np

lista = [1, 2, 3, 4, 5]

#Respuesta
lista

[1, 2, 3, 4, 5]

### Crear un array de ceros de tamaño 5x5

In [4]:
#Código crear un array de ceros de tamaño 5x5
arr_ceros = np.zeros((5,5)) #Crea arreglo 5x5 de ceros
arr_ceros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Crear un array de unos de tamaño 3x3

In [6]:
#Código crear un array de unos de tamaño 3x3
arr_unos = np.ones((3,3)) #Crea arreglo 3x3 de unos
arr_unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Crear un array con valores espaciados uniformemente de 0 a 9

In [22]:
#Código rear un array con valores espaciados uniformemente de 0 a 9
arr = np.random.uniform(10, size=5) 
arr

array([1.77592844, 3.98588993, 3.01817258, 6.22820258, 8.81730004])

### #Crear un array con 6 valores espaciados linealmente entre 0 y 1


In [16]:
#Código crear un array con 6 valores espaciados linealmente entre 0 y 1
arr = np.random.rand(6)
arr

array([0.6719481 , 0.68500229, 0.36329162, 0.85094984, 0.39627677,
       0.45024012])

# Operaciones Básicas

### Realizar una suma, resta, multiplicación y división entre dos arrays

In [10]:
array_1 = np.array([5,4,2])
array_2 = np.array([6,4,9])

#Código realizar una suma, resta, multiplicación y división entre dos arrays
suma = np.add(array_1,array_2) #Suma de arreglos
resta = np.subtract(array_1,array_2) #Resta de arreglos
multiplicacion = array_1 * array_2 #Multiplicacion de arreglos
division = array_1 / array_2 #Division de arreglos

# Salida

print("La suma es: ",suma)
print("La resta es: ",resta)
print("La multiplicacion es: ",multiplicacion)
print("La division es: ",division)


La suma es:  [11  8 11]
La resta es:  [-1  0 -7]
La multiplicacion es:  [30 16 18]
La division es:  [0.83333333 1.         0.22222222]


In [47]:
#Calcular el producto punto de dos arrays
a = [5, 10]
b = [4, -7]
dot_product = np.dot(a, b) #producto punto de arrays a y b

print(dot_product)

-50


In [23]:
#Transponer un array
arr = np.array([[7,8,9],[4,5,6]])
arr.T #transpone arreglos

array([[7, 4],
       [8, 5],
       [9, 6]])

# Operaciones Estadísticas

In [42]:
#Calcular la media, suma, valor mínimo y valor máximo de un array

arr = np.arange(1,101) #Crea arreglo
media = arr.mean() #Calcula media de arreglo
suma = arr.sum() #Suma arreglo
minimo = arr.min() #Calcula minumo del arreglo
maximo = arr.max() #calcula maximo del arreglo

print(media)
print(suma)
print(minimo)
print(maximo)

50.5
5050
1
100


In [43]:
#Cambiar la forma de un array "reshape"
arr = np.arange(1,101).reshape(5,20)
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,
         34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
         54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
         74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
         94,  95,  96,  97,  98,  99, 100]])

# Álgebra Lineal

### Calcular el determinante de una matriz 2x2

In [44]:
nuevo_array = np.array([[1,2],[2,5]])

#Código para calcular el determinante de una matriz 2x2
determinante = np.linalg.det(nuevo_array)
#print(determinante)
print(determinante)

1.0


### Calcular la matriz inversa de una matriz 3x3

In [45]:
# Definir la matriz 3x3
matriz = np.array([[3, 4, -1], [2, 0, 1], [1, 3, -2]])

# Calcular la matriz inversa
matriz_inversa = np.linalg.inv(matriz)

# Imprimir la matriz inversa
print(matriz_inversa)


[[-0.6  1.   0.8]
 [ 1.  -1.  -1. ]
 [ 1.2 -1.  -1.6]]


### Calcular los valores propios y vectores propios de una matriz 4x4

In [15]:

# Definir la matriz 4x4
matriz_4x4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

# Calcular valores propios y vectores propios

autovalores, autovectores = np.linalg.eig(matriz_4x4)


# Separar valores propios y vectores propios
 # Parte real de los valores propios complejos
  # Parte real de los vectores propios complejos

# Imprimir resultados

print("Valores propios:", autovalores)
print("Vectores propios:")
for i in range(len(autovectores)):
    print(f"Vector propio {i+1}:", autovectores[i])


Valores propios: [ 3.62093727e+01 -2.20937271e+00 -2.62410379e-15 -9.51420961e-17]
Vectores propios:
Vector propio 1: [-0.15115432 -0.72704996 -0.47688035 -0.07702174]
Vector propio 2: [-0.34923733 -0.28320876  0.83665151 -0.30149603]
Vector propio 3: [-0.54732033  0.16063243 -0.24266197  0.83405728]
Vector propio 4: [-0.74540333  0.60447363 -0.11710919 -0.45553951]


# Funciones Universales

In [16]:
# Crear un array con ángulos
array_angulos = np.array([0, np.pi/2, np.pi])

# Calcular el seno de los ángulos
seno = np.sin(array_angulos)

# Calcular el coseno de los ángulos
coseno = np.cos(array_angulos)

# Calcular la exponencial de los ángulos
exponencial = np.exp(array_angulos)

# Calcular el logaritmo natural de los ángulos
log_nat = np.log(array_angulos)

print(seno)
print(coseno)
print(exponencial)
print(log_nat)


[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 1.          4.81047738 23.14069263]
[      -inf 0.45158271 1.14472989]


C:\Users\salazaor\AppData\Local\Temp\ipykernel_19992\2224688277.py:14: RuntimeWarning: divide by zero encountered in log
  log_nat = np.log(array_angulos)


In [8]:
#Realizar indexación y slicing en un array 2D

# Crear un array NumPy bidimensional
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Obtener la primera fila del array
primera_fila = array_2d[0] 

# Obtener la última columna del array
  # [3, 6, 9]
ultima_columna = array_2d[:, -1]

# Obtener una submatriz que contiene la segunda fila y las dos primeras columnas
  # [4, 5]
submatriz = array_2d[1, :2]

# Imprimir los subconjuntos de datos extraídos
print(primera_fila)
print(ultima_columna)
print(submatriz)

[1 2 3]
[3 6 9]
[4 5]


# Generación de Números Aleatorios

In [10]:
#Generar un array de 10 números enteros aleatorios entre 1 y 100
array_10 = np.random.randint(1, 101, size=10)

print(array_10)

[34 38 25 21 24 55 93 62 78 12]


In [11]:
#Generar una matriz 2x3 con números aleatorios uniformemente distribuidos entre 0 y 1
matriz_uniforme = np.random.uniform(low=0, high=1, size=(2, 3))

print(matriz_uniforme)

[[0.97936982 0.28558443 0.80102015]
 [0.3720089  0.27862063 0.57592006]]


In [12]:
#Generar un array de 5 números aleatorios con distribución normal (media 0, desviación estándar 1)
datos_normal = np.random.normal(0, 1, 5)

print(datos_normal)


[ 0.26185378  0.3827334  -0.80571547  0.5235022   0.07578002]
